# Generated by Django 5.2.8 on 2026-04-30 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('fisier_pdf', models.FileField(upload_to='materiale_pdf/')),
                ('data_incarcarii', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parola', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('elev', 'Elev'), ('profesor', 'Profesor')], default='elev', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('material_sursa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.material')),
            ],
        ),
        migrations.CreateModel(
            name='Intrebare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_intrebare', models.TextField()),
                ('varianta_a', models.CharField(max_length=200)),
                ('varianta_b', models.CharField(max_length=200)),
                ('varianta_c', models.CharField(max_length=200)),
                ('varianta_d', models.CharField(max_length=200)),
                ('raspuns_corect', models.CharField(max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrebari', to='myapp.test')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='autor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.utilizator'),
        ),
    ]
