# Generated by Django 5.2.8 on 2026-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parola', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('elev', 'Elev'), ('profesor', 'Profesor')], default='elev', max_length=10)),
            ],
        ),
    ]
