# Generated by Django 5.2.8 on 2026-03-19 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='autor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.utilizator'),
        ),
    ]
