# Generated by Django 5.2.8 on 2026-05-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_test_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_materie', models.CharField(max_length=100)),
                ('specializare', models.CharField(max_length=100)),
                ('cod_inrolare', models.CharField(blank=True, max_length=8, unique=True)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='clasele_mele', to='myapp.utilizator')),
                ('studenti', models.ManyToManyField(blank=True, related_name='clase_inrolate', to='myapp.utilizator')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='clasa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiale', to='myapp.clasa'),
        ),
        migrations.AddField(
            model_name='test',
            name='clasa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teste', to='myapp.clasa'),
        ),
    ]
