# Generated by Django 5.2.8 on 2026-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_clasa_material_clasa_test_clasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasa',
            name='an_studiu',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
