# Generated by Django 5.2.8 on 2026-03-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_material_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('material_sursa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.material')),
            ],
        ),
        migrations.CreateModel(
            name='Intrebare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_intrebare', models.TextField()),
                ('varianta_a', models.CharField(max_length=200)),
                ('varianta_b', models.CharField(max_length=200)),
                ('varianta_c', models.CharField(max_length=200)),
                ('varianta_d', models.CharField(max_length=200)),
                ('raspuns_corect', models.CharField(max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrebari', to='myapp.test')),
            ],
        ),
    ]
