# Generated by Django 5.2.8 on 2026-06-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rezultattest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.IntegerField()),
                ('tip', models.CharField(choices=[('TEST', 'Test Online'), ('ACTIVITATE', 'Activitate la clasă')], default='TEST', max_length=20)),
                ('data_acordarii', models.DateField(auto_now_add=True)),
                ('clasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clasa')),
                ('student', models.ForeignKey(limit_choices_to={'rol': 'elev'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.utilizator')),
            ],
        ),
    ]
