# Generated by Django 5.2.8 on 2026-06-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.test'),
        ),
    ]
